version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1569999
      POSTGRES_DB: postgres  # You might want to specify the database name here if needed
  nestjs:
    build: .
    ports:
      - "4000:4000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1569999
      JWT_SECRET: "my-secret-key"
    depends_on:
      - postgres